version: "3"
services:
    app:
        build:
            context: ../../
            dockerfile: local.Dockerfile
        container_name: app
        env_file:
            - .env
        tty: true
        ports:
            - ${PORT}:${PORT}
        volumes:
            - type: bind
              source: ../../api/go
              target: /api/go
            - type: bind
              source: ../../front
              target: /front
        depends_on:
            db:
                condition: service_healthy

    db:
        build:
            context: ../../api/sql
        container_name: db
        environment:
            - MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
        restart: always
        volumes:
            - type: bind
              source: ../sql-data
              target: /var/lib/mysql
            - type: bind
              source: ../../api/sql/0_init.sql
              target: /docker-entrypoint-initdb.d/0_init.sql
              read_only: true
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 10s
            timeout: 5s
            retries: 20
