version: "3"
services:
    app:
        image: moririn2528/timetable-app:latest
        container_name: app
        environment:
            - PORT
            - SQL_DSN
        tty: true # 永続化
        ports:
            - ${PORT}:${PORT}
        volumes:
            - type: bind
              source: ./log/go.log
              target: /api/go/1.log
        depends_on:
            - db

    db:
        image: moririn2528/timetable-db:latest
        container_name: db
        environment:
            - MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
        restart: always
        volumes:
            - type: bind
              source: ../sql-data
              target: /var/lib/mysql
            - type: bind
              source: ../../api/sql/1.sql
              target: /docker-entrypoint-initdb.d/1.sql
              read_only: true
